scripts:
  - name: Make gradlew executable
    script: chmod +x gradlew

  - name: Setup local.properties
    script: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

  - name: Clean build
    script: ./gradlew clean --no-daemon

  - name: Build APK
    script: ./gradlew assembleDebug --no-daemon
